version: '2'
volumes:
  settings:
  iobrokerdata:
  homeassistant:
  openhab_addons:
    driver: local
  openhab_conf:
    driver: local
  openhab_userdata:
    driver: local
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    network_mode: host
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    restart: always
    build: ./wifi-connect
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  raspap:
    restart: always
    image: jrcichra/raspap-docker
    container_name: raspap
    hostname: raspap
    privileged: true
    network_mode: host
    cap_add:
      - SYS_ADMIN
    labels:
      io.balena.features.sysfs: '1'
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    privileged: true
    network_mode: host
    volumes:
      - 'iobrokerdata:/opt/iobroker'
  homeassistant:
    restart: always
    image: homeassistant/raspberrypi4-homeassistant:stable
    container_name: homeassistant
    hostname: homeassistant
    network_mode: host
    privileged: true
    volumes:
      - 'homeassistant:/config'
  openhab:
    restart: always
    image: 'openhab/openhab:3.0.2'
    container_name: openhab
    hostname: openhab
    network_mode: host
    privileged: true
    volumes:
      - 'openhab_addons:/openhab/addons'
      - 'openhab_conf:/openhab/conf'
      - 'openhab_userdata:/openhab/userdata'
    environment:
      OPENHAB_HTTP_PORT: '8085'
      OPENHAB_HTTPS_PORT: '8443'
      EXTRA_JAVA_OPTS: '-Duser.timezone=Europe/Berlin'
