version: '2'
volumes:
  settings:
  iobrokerdata:
  homeassistant:
services:
  kiosk:
    restart: always
    build: ./kiosk
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'settings:/data'
  scheduler:
    restart: always
    build: ./scheduler
    privileged: true
  wifi-connect:
    restart: always
    build: ./wifi-connect
    network_mode: host
    privileged: true
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.firmware: '1'
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    privileged: true
    network_mode: host
    volumes:
      - 'iobrokerdata:/opt/iobroker'
  homeassistant:
    restart: always
    image: homeassistant/raspberrypi4-homeassistant:stable
    container_name: homeassistant
    hostname: homeassistant
    network_mode: host
    privileged: true
    volumes:
      - 'homeassistant:/config'
